### ISSUE TITLE
LGadget2 total number of particles

### ISSUE THREAD

**Issue by manodeep** [phil-mansfield/shellfish#136]
Looks very promising - thanks for writing the code! 

I did have a question about reading LGadget files. In the standard LGadget header file, the total number of particles is split into `npartTotal[1]` and `npartTotal[2]` like so (from Roman's original implementation [here](http://cosmo.nyu.edu/roman/2LPT/)
      
      header.npartTotal[1] = TotNumPart;
      header.npartTotal[2] = (TotNumPart >> 32); //TotNumPart is a 64 bit integer

Correspondingly, I think the reads should reference `header.npartTotal[2]` but I only see references to `header.Npart[0]`. Apologies in advance if this is not true for your IC code. 

On a related note, if `C` rules are valid in `go`, then `header.npart[0] << 32` left-shifts a 32 bit variable by 32 bits and constitutes undefined behaviour (generally speaking, you will end up with the original value of `header.npart[0]`). If you want to use those 32 bits as the upper 32 bits in `count` [e.g., here](https://github.com/phil-mansfield/shellfish/blob/master/io/lgadget2.go#L81) then you will have to cast `npart[0]` to 64 bits first, and then perform the left-shift.

**Comment by phil-mansfield** [comment]
Thanks for checking this. I really appreciate it.

Left shifting a 32 bit integer won't be undefined behavior in Go, but my impression was that it shouldn't result in the correct behavior, as you say. This is confusing to me, because I've successfully tested this reader on Gadget files with more than 4 million particles in them. Nonetheless, I've pushed a fix for this particular bug to master.

The second problem brought up here regards which element of `npart` contains the least and most signficant digits of the total number of particles. Looking at the code you have linked to and at some other gadget-reading code I have access to, it appears that this might be version-specific behavior (or, maybe, there are numerous people who do it incorrectly one way or the other, which is effectively the same thing). I'll decide what the correct way to deal with this is tomorrow.

A very related issue (not brought up here) is the use of `int` vs. `int64` to represent the number of particles in a single block. Go defines the length of an `int` to be at least 32 bits with the implication that all 64 bit systems (and many 32 bit system) will have int sizes be 64 bits, implying that if a user had individual block files that were larger than 128 GB would run into very confusing errors. This isn't solved simply, because the maximum addressable space on a 32 bit machine would be smaller than the size of the positions array.

On one hand, I feel like this would be a rather unlikely scenario and adapting to it would significantly complicate many parts of Shellfish's implementation, but on the other it would be a shame not to support completely legal file configurations. I think the correct approach right now would be to explicitly check for this case, to throw a very clear error, and defer this until user request.

**Comment by manodeep** [comment]
Thanks for the quick response. The fix looks fine and since it looks like `npart[0]` does indeed contain the overflow, then I agree that the best way would be to simply warn the user if potentially `npartTotal[2]` contains the overflow particles. If you are only reading a single file with dark-matter-only, then everything should be fine. `npart[0]` would be 0, and the number of particles *in that file* will be fine. My comment only applies when performing an aggregate read over multiple files per snapshot. 

I am confused about the integer size in Go comment though. C also has very similar "specifications" about the size of `int/long` (with `int = 2` or `4` bytes and `long = 4` or `8` bytes, platform dependent). However, I would think that the binary layout in Go **must match** that generated by the C compiler during the simulation. Otherwise, the data read in should be garbage. 

(I am assuming the reference to 4 million particles is a typo, int overflow occurs at 2^31-1 = 2147483647 particles. All of the int overflow corrections only become important when the total number of particles, summed across all files, exceeds this ~2.1 billion.)

**Comment by phil-mansfield** [comment]
Allow me to clarify a bit about Shellfish's architecture: your concern about reading in multiple files would normally be correct, but I handle things a bit differently. The entire underlying simulation is never stored in memory at one time: only one block is ever loaded into memory at a time as a performance/memory optimization. The total number of particles in the simulation is never used. The problem I was referring to was is the user was running Shellfish on a 32-bit machine to read Gadget files which had been created on a 64-bit and each _individual_ file contained more than 2 billion (as you point out, I was wrong to say 4 billion) particles. My sense is that this is an uncommon situation, but it would be good to crash with a descriptive error nonetheless.

Another clarification is that Go integers are not meant to be analogs to C integers. (Go has these if you need them, but they're called `C.int`.) Additionally, I do not use variable-width integers for binary I/O because I don't want the behavior of Shellfish to be platform dependent and because there's never a guarantee that the file you're reading was generated on the same machine that Shellfish is running on. If the file specification uses variable width integers, my preferred approach is to have multiple fixed-width structs and explicitly select the one which applies.

So then the question is what Gadget's file specifications actually are. Unfortunately, it looks like there isn't one correct answer to this. Page 33 of [Gadget's user guide](https://wwwmpa.mpa-garching.mpg.de/gadget/right.html#User%27s%20Guide) specifies that each element of `Npart` is of type `uint`, line 611 of Gadget's `allvars.h`defines them as being type `int`, and line 28 of N-genIC's `allvars.h` defines them to be exactly 4 bytes wide. Additionally, a quick survey of different Gadget reading/writing packages on the web reveals inconsistent behavior: some treat `Npart` as being with width of a C int and some as being 4 bytes ( yt is probably the most popular of these types of packages and defines `Npart` as being 4 bytes). Eeek.

I think the right approach is to add an optional field in the config files for Shellfish where the user can specify the width of integers in their Gadget header. If they don't know or don't want to specify, Shellfish can assume what most analysis packages assume (and what it currently assumes), which is 4 byte integers.

**Comment by manodeep** [comment]
Thanks again for the detailed and quick response. 

For a valid (L)Gadget file, the max. size of `npart` is `INT_MAX/(3*4)`. This constraint comes from the padding bytes, before and after an (L)Gadget `pos/vel/accel` field, that contain the number of bytes in the field. If `npart` is more than `INT_MAX/(3*4)` ~ 179 million, then the field padding bytes themselves overflow. Since these padding bytes are typically assigned to an `int` in (L)Gadget, the result of this overflow is undefined. However in practice, most systems I have been on follow the same semantics as `unsigned int` overflow for `int` overflow as well. That's why the real limit for the number of particles is actually lower than `INT_MAX` and reading it back either as `int` or `uint` should not make any difference. From my experience, `npart` is an `int`, `npartTotal` is *always* `unsigned int`. 

You can safely assume that the `int` types in (L)Gadget are 4 bytes. This is somewhat essential, since reading the binary file back in becomes very difficult otherwise. In the first version of Gadget, there were typedefs (`int4byte`, if memory serves right) to ensure that the integers were 4 bytes. Note that that Gadget version pre-dates `<stdint.h>` -- so there was no concept of `(u)int32_t` at the time. 

As far as the multiple fixed-width structs, I am curious -- how do you know which one is the correct one in the general case? The file could have been generated elsewhere and copied over. 

Thanks!

**Comment by phil-mansfield** [comment]
That's a good point about the padding bytes.

The simplest way to know which width is used (or what endianness is used) is to ask the user. You can have a flag that can be set to `SystemWidth` | `32Bit` | `64Bit` | ... with the default behavior being to use the system width for integers (or some other width if you know better), so if they don't do anything they get the behavior they would have gotten if had used variable width ints in the first place. If you know something about the underlying data, you could check fields where values are relatively tightly bounded. If you can demonstrate that valid values for those fields can't be reached if type widths change (and/or if endianness changes), you can test reading the file with the different fixed width structs and find the only one which contains a valid value for that field.

Really, the ideal way to handle this is to either have a file format where endianness and integer width are part of the formal specification, or to have a field somewhere early in that file that unambiguously specifies them. But that's only an option if you're designing the format in the first place.

**Comment by manodeep** [comment]
Thanks again. I think we are on the same page - binary format by default should really be a last resort now. But designing an "optimal" file format is left as an exercise to the reader :)

Please feel free to close this issue if you would like. Thanks again.

**Comment by phil-mansfield** [comment]
Okay, sounds good. Thanks for bringing this up.
